### ISSUE TITLE
Precision on if the CB Gateway should stay up & running (or not) regarding Swarm/Baywatch components

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak-docs#6]
Hi,

On Operations page, it's stated:

```
Cloudbreak gateway node

With every Cloudbreak cluster installation there is a special node called cbgateway started that won't run an ambari-agent container so it won't run HDP services either. It can be seen on the Cloudbreak UI among the hostgroups when creating a cluster, but its node count cannot be changed from 1 and it shouldn't be there in the Ambari blueprint. It is by design because this instance has some special tasks:

    it runs the Ambari server and its database inside Docker containers
    it runs an nginx proxy that is used by the Cloudbreak API to communicate with the cluster securely
    it runs the Swarm manager that orchestrates the Docker containers on the whole cluster
    it runs the Baywatch server that is responsible for collecting the operational logs from the cluster
    it runs a Kerberos KDC container if Kerberos is configured
```

Regarding Swam & Baywatch part, does it mean that Cloudbreak gateway should stay up & running 24/7

So far, my ops team just power up CB Gateway when we create a new cluster, but once it's created, CB GAteway instance is stopped.

When reading the doc, I would let it up and running but if you could confirm and maybe precise in the docs, I would appreciate.

Thanks,
Nicolas

**Comment by matyix** [comment]
Hi Nicolas. What would you like to achieve and which platform? If you'd like to stop the cluster alltogether you can do with the stop function (button) - when you restart we take care of everything. If you'd like to decrease the cluster size you can do with the autoscaling feature by bringing the cluster size down to the minimum (e.g. 1 node f your date is on S3 or WASB for example).

**Comment by nsteinmetz** [comment]
Hi @matyix,

I will precise:
* We use so far Cloudbreak on AWS and related HDP cluster on AWS too.
* So far, CB Gateway was just used to initiate cluster via blueprints for prod & non prod envts. Once cluster is up and running, ops team shut down the CB gateway ; but rest of the cluster remains up and running.
* When I read CB docs above, I understand that I should keep CB Gateway up and running all the time at least for the Swarm & Baywatch components to work as expected. Is it required or not ?
* We do not use autoscalling yet even if we will soon. From my understanding, it will require to have CB Gateway up & running 24/7 and enable periscope so that autoscalling can be managed via CB.

So regarding the 3rd bullet, I just want to know if in a non autoscaling context, I should keep CB Gateway up and running as it is required or if it's safe to shutdown CB Gateway when we don't use it to add / stop  / delete a HDP cluster.

**Comment by matyix** [comment]
Hi

The Gateway node is running the Ambari server - if you'd like to use the Ambari UI for whatever purpose (monitoring, management, etc) you will have to keep the gateway node up and running. Also if you'd like to have Cloudbreak  to do post cluster provisioning operations (autoscaling, manually add/remove nodes, etc) you still need to node.

if you mere goal is to provision an HDP cluster and then you don't want to do nothing else you can terminate the node - the problem is that after that point all the operations will be on your behalf, Cloudbreak can not talk to that cluster anymore. From functional/operational perspective the HDP cluster is fully functional without the Gateway node, though.

**Comment by nsteinmetz** [comment]
Thanks for the precision ; one doubt however: for me the ambari server is on the edge node as I can acccess a working ambari UI and do things (like install component or deploy configuration) with CB Gateway down. So I would think that one implementation is to have Ambari Server on CB Gateway node but it's not mandatory, we can set it on the edge node via our blueprint. Correct ?

**Comment by akanto** [comment]
Hi,

The Ambari server is running on CB Gateway node, there is no option to put anywhere else. The components on edge node are installed by Ambari server, but the Ambari server cannot install an another Ambari Server on the edge node.

Attila

**Comment by nsteinmetz** [comment]
Hi @akanto,

My bad indeed ; cbgatewaynode and edge node are the same vm. I confused this vm with Cloudbreak Deployer vm.

So putting all the things in the right order:
* Cloudbreak gateway node is up and running 24/7 in our context.
* To set up a new cluster or stop/delete an existing one, I need to use Cloudbreak Deployer. Otherwise it can be shut down.
* Scaling policy or recipes can be used by using CB Gateway node & Ambari. Cloudbreak deployer is not required
* Periscope is to be enabled on the CB Gateway node too to enable autoscaling. But this is to be done via the Cloudbreak deployer when defining the blueprint ; correct ?

Hope I'm clear now ; thanks for your precision and your quick answers.

**Comment by akanto** [comment]
Hi @nsteinmetz,

* To set up a new cluster or stop/delete an existing one, I need to use Cloudbreak Deployer. Otherwise it can be shut down.

The Cloudbreak Deployer node is usually the same as the Cloudbreak node, since the Cloudbreak Deployer is starting the Cloudbreak + supporting containers on the same node where the Cloudbreak Deployer was invoked.
This means that you need to use the Cloudbreak Deployer/Cloudbreak node when you would like to stop/start a cluster or scale the cluster.

* Scaling policy or recipes can be used by using CB Gateway node & Ambari. Cloudbreak Deployer is not required

The Cloudbreak Deployer is basically just a command line tool and you don't need it after you have started Cloudbreak. You are right Cloudbreak is needed when you would like to stop/start a cluster or scale the cluster, otherwise it can be shut down.

* To set up a new cluster or stop/delete an existing one, I need to use Cloudbreak Deployer. Otherwise it can be shut down.
You need the Cloudbreak Deployer (single binary command line tool) to start the Cloudbreak (web application running inside docker containers and manages your clustert by starting stoping VMs, installing Ambari Server etc. ).

Attila

**Comment by nsteinmetz** [comment]
Thanks a lot; it's clear now ! :)
